name = "my-worker"
main = "src/index.ts"
compatibility_date = "2025-07-16"

#routes = ["cfhomework.hxn-cf.com/secure*"]
routes = [
  "https://cfhomework.hxn-cf.com/secure*",
  "https://tunnel.hxn-cf.com/secure*",
  "https://www.hxn-cf.com/secure*",
  "https://tunnel.hxn-cf.com/login*",
  "https://cfhomework.hxn-cf.com/login*",
  "https://www.hxn-cf.com/login*"
]

zone_id = "3f1534c91a608a452bde151a8d83bd8f"

[[r2_buckets]]
binding = "FLAGS_BUCKET"
bucket_name = "flags"
preview_bucket_name = "flags"


