name = "my-worker"
main = "src/index.ts"
compatibility_date = "2025-07-16"

routes = ["tunnel.ha1x1angwebsite.com/secure*"]
zone_id = "004d808ea928375457ed1187c4a4b5fb"

[[r2_buckets]]
binding = "FLAGS_BUCKET"
bucket_name = "flags"
preview_bucket_name = "flags"


